dist: trusty
language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=512m -Xmx2g"
    - CODECOV_TOKEN="d4c4d4bd-a302-43a4-ba0f-c0bf6b5ebe9c"
script: ./build.sh
